// Default stone colors sorted alphabetically
export const DEFAULT_STONE_COLORS = [
  'Lt.Colorado Topaz',
  'Citrine',
  'Silver Hematite',
  'Lt.Peach',
  'Montana',
  'Cosmojet',
  'Lt.Brown-Tea',
  'Ab Crystal-janjanlı',
  'Hematite',
  'Topaz',
  'Joungle',
  'Lt.Amethyst',
  'Rainbow',
  'Violet',
  'Champagne',
  'Erinite-Blue Zircon',
  'Turkuaz',
  'Lt.Topaz',
  'Rosepink',
  'Ab Topaz',
  'Gold Hematite',
  'Cobalt',
  'Siam',
  'Lt Siam',
  'Emerald',
  'Black',
  'Pink',
  'Smoked Topaz',
  'Lt.Saphire',
  'Peridot',
  'Saphire',
  'Hyacinth',
  'Black Diamond',
  'Amethyst',
  'Crystal',
  'Jet',
  'Jet Hematite'
].sort();